version: "3.7"

services:
  app:
    build:
      context: ./app
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  celery:
    build:
      context: ./app
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    volumes:
      - ./app/:/usr/src/app/
    command: pipenv run celery -A appcenter worker -l info
    env_file:
      - .env
  redis:
    image: redis:alpine

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=facade-inspector
      - POSTGRES_PASSWORD=&wpTP2?asSu9r6!n
      - POSTGRES_DB=facade-inspector
volumes:
  postgres_data:
