[tool.isort]
profile = "black"

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | ^.*\b(migrations)\b.*$,
  | migrations
)/
'''
skip-string-normalization = 1
skip-magic-trailing-comma = 1